### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by Edward-ba**
eagler doesn't need to use a relay bro

### CODE REVIEW

**Comment by leahanderson1** [comment]
the project that *used* to be hosted on this github had a relay system to allow for java support.

**Comment by grandpa1946** [comment]
> the project that _used_ to be hosted on this github had a relay system to allow for java support.

do you mean it's hosted elsewhere right now?

**Comment by leahanderson1** [comment]
i have the files, i'll push them to an alternate git site soon

**Comment by grandpa1946** [comment]
> i have the files, i'll push them to an alternate git site soon

codeberg, gitlab, ...?

**Comment by leahanderson1** [comment]
[prob this one](https://repo.or.cz/)

**Comment by grandpa1946** [comment]
> [prob this one](https://repo.or.cz/)

"90s layout!

**Pull request merged**
